### ISSUE TITLE
Writes deprecation terminal output to file

### ISSUE THREAD

**Issue by AadityaRavindran** [embear/vim-uncrustify#2]
If the uncrustify config is using deprecated commands, for example `sp_cpp-lambda_paren`, then on running `:Uncrustify` from vim (nvim in my case), apart from updating the file with actual uncrustify changes, it adds `option 'sp_cpp_lambda_paren' is deprecated; use 'sp_cpp_lambda_square_paren' instead` to the start of the file.

**Comment by embear** [comment]
Sorry for being so late!
This should be fixed with latest master

**Comment by AadityaRavindran** [comment]
No worries. Thanks for the fix. It works
