### ISSUE TITLE
not working after updating

### ISSUE THREAD

**Issue by JaeheeKwon** [embear/vim-uncrustify#3]
After updating it to the latest commit(6b647253c9de0283a1b7ef4a49b930c6e43d7fd2), it stops working.
I can confirm that the previous commit works fine on Mac and WSL.

**Comment by embear** [comment]
Sorry for the inconvenience! I made a mistake in my last commit and did not recognize the problem because I am not using this plugin myself anymore. Should be fixed with the latest commit.

**Comment by JaeheeKwon** [comment]
NP. Thank you!
